project:
  type: website
  output-dir: _site

website:
  title: "Best Practices in Python Workshop"
  open-graph: true
  bread-crumbs: false
  navbar:
    pinned: false
    tools-collapse: true
    background: "primary"
    right:
      - icon: github
        href: https://github.com/TheJacksonLaboratory/bestpractices_workshop
        aria-label: GitHub repository

  sidebar:
    style: "floating"
    contents:
      - text: Virtual Environments
        href: conda.md
      - text: Testing
        href: pytest.md
      - text: Docstrings & Linting
        href: docstrings.md
      - text: Type Hints
        href: typing.md
  page-navigation: true

  search:
    location: sidebar
    type: textbox
    show-item-context: true

  repo-url: "https://github.com/TheJacksonLaboratory/bestpractices_workshop"
  repo-actions: [source, edit, issue]

format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: true
    search: true
    theme:
      light: cosmo
      dark: cyborg
    respect-user-color-scheme: true


date: last-modified
license: "CC BY"